"""Render changelog of agent config changes as Markdown or JSON."""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import UTC, datetime

import structlog

from licit.core.models import ChangeSeverity, ConfigChange

logger = structlog.get_logger()

_SEVERITY_LABEL: dict[ChangeSeverity, str] = {
    ChangeSeverity.MAJOR: "MAJOR",
    ChangeSeverity.MINOR: "MINOR",
    ChangeSeverity.PATCH: "PATCH",
}

_SEVERITY_ORDER: dict[ChangeSeverity, int] = {
    ChangeSeverity.MAJOR: 0,
    ChangeSeverity.MINOR: 1,
    ChangeSeverity.PATCH: 2,
}


class ChangelogRenderer:
    """Renders a list of ConfigChange into Markdown or JSON."""

    def render(self, changes: list[ConfigChange], fmt: str = "markdown") -> str:
        """Render changes in the requested format."""
        if fmt == "json":
            return self._render_json(changes)
        return self._render_markdown(changes)

    def _render_markdown(self, changes: list[ConfigChange]) -> str:
        """Render changes as a Markdown changelog."""
        if not changes:
            return "# Agent Config Changelog\n\nNo changes detected.\n"

        lines: list[str] = ["# Agent Config Changelog\n"]

        # Group changes by file
        by_file: dict[str, list[ConfigChange]] = defaultdict(list)
        for ch in changes:
            by_file[ch.file_path].append(ch)

        # Summary
        major = sum(1 for c in changes if c.severity == ChangeSeverity.MAJOR)
        minor = sum(1 for c in changes if c.severity == ChangeSeverity.MINOR)
        patch = sum(1 for c in changes if c.severity == ChangeSeverity.PATCH)
        lines.append(
            f"> {len(changes)} change(s) detected across {len(by_file)} file(s): "
            f"**{major}** major, **{minor}** minor, **{patch}** patch\n"
        )

        # Per-file sections
        for file_path in sorted(by_file.keys()):
            file_changes = by_file[file_path]
            # Sort by severity (major first), then by timestamp descending
            file_changes.sort(
                key=lambda c: (_SEVERITY_ORDER.get(c.severity, 9), -c.timestamp.timestamp())
            )

            lines.append(f"## {file_path}\n")

            for ch in file_changes:
                label = _SEVERITY_LABEL.get(ch.severity, "PATCH")
                sha_part = f" (`{ch.commit_sha[:8]}`)" if ch.commit_sha else ""
                date_part = ch.timestamp.strftime("%Y-%m-%d")
                lines.append(f"- **[{label}]** {ch.description}{sha_part} — {date_part}")

            lines.append("")

        lines.append(
            f"---\n*Generated by licit at "
            f"{datetime.now(tz=UTC).strftime('%Y-%m-%d %H:%M UTC')}*\n"
        )
        return "\n".join(lines)

    def _render_json(self, changes: list[ConfigChange]) -> str:
        """Render changes as JSON."""
        records = [
            {
                "file_path": ch.file_path,
                "field_path": ch.field_path,
                "old_value": ch.old_value,
                "new_value": ch.new_value,
                "severity": str(ch.severity),
                "description": ch.description,
                "timestamp": ch.timestamp.isoformat(),
                "commit_sha": ch.commit_sha,
            }
            for ch in changes
        ]
        return json.dumps({"changes": records}, indent=2, ensure_ascii=False)
