"""Generate provenance summary reports in Markdown format."""

from __future__ import annotations

from collections import Counter
from datetime import datetime
from pathlib import Path

import structlog

from licit import __version__
from licit.core.models import ProvenanceRecord

logger = structlog.get_logger()


def generate_provenance_report(
    records: list[ProvenanceRecord],
    output_path: str,
) -> None:
    """Generate a Markdown provenance report from records.

    Args:
        records: List of provenance records to summarize.
        output_path: Path to write the Markdown report.
    """
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    report = _build_report(records)

    Path(output_path).write_text(report, encoding="utf-8")
    logger.info("provenance_report_generated", path=output_path, records=len(records))


def _build_report(records: list[ProvenanceRecord]) -> str:
    """Build the Markdown content for a provenance report."""
    # Deduplicate: latest record per file wins
    latest: dict[str, ProvenanceRecord] = {}
    for r in records:
        existing = latest.get(r.file_path)
        if existing is None or r.timestamp > existing.timestamp:
            latest[r.file_path] = r

    total = len(latest)
    ai_files = [r for r in latest.values() if r.source == "ai"]
    human_files = [r for r in latest.values() if r.source == "human"]
    mixed_files = [r for r in latest.values() if r.source == "mixed"]

    ai_pct = round(len(ai_files) / max(total, 1) * 100, 1)
    human_pct = round(len(human_files) / max(total, 1) * 100, 1)
    mixed_pct = round(len(mixed_files) / max(total, 1) * 100, 1)

    # Count agents and models
    agents: Counter[str] = Counter()
    models: Counter[str] = Counter()
    for r in latest.values():
        if r.agent_tool:
            agents[r.agent_tool] += 1
        if r.model:
            models[r.model] += 1

    lines = [
        "# Provenance Report",
        "",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total files | {total} |",
        f"| AI-generated | {len(ai_files)} ({ai_pct}%) |",
        f"| Human-written | {len(human_files)} ({human_pct}%) |",
        f"| Mixed | {len(mixed_files)} ({mixed_pct}%) |",
        "",
    ]

    if agents:
        lines.extend([
            "## AI Tools Detected",
            "",
            "| Tool | Files |",
            "|------|-------|",
        ])
        for agent, count in agents.most_common():
            lines.append(f"| {agent} | {count} |")
        lines.append("")

    if models:
        lines.extend([
            "## Models Detected",
            "",
            "| Model | Files |",
            "|-------|-------|",
        ])
        for model, count in models.most_common():
            lines.append(f"| {model} | {count} |")
        lines.append("")

    # File details
    lines.extend([
        "## File Details",
        "",
        "| File | Source | Confidence | Method | Agent |",
        "|------|--------|------------|--------|-------|",
    ])

    for file_path in sorted(latest):
        r = latest[file_path]
        agent_str = r.agent_tool or "-"
        # Escape pipes in file paths to avoid breaking markdown tables
        safe_path = r.file_path.replace("|", "\\|")
        lines.append(
            f"| {safe_path} | {r.source} | {r.confidence:.0%} "
            f"| {r.method.value} | {agent_str} |"
        )

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by licit v{__version__}*")
    lines.append("")

    return "\n".join(lines)
