"""HTML report renderer — single-file, no external dependencies."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from licit.core.models import ControlResult
    from licit.reports.unified import FrameworkReport, UnifiedReport

_STATUS_COLORS: dict[str, str] = {
    "compliant": "#22c55e",
    "partial": "#f59e0b",
    "non-compliant": "#ef4444",
    "n/a": "#9ca3af",
    "not-evaluated": "#6b7280",
}


def render(report: UnifiedReport) -> str:
    """Render a UnifiedReport as a self-contained HTML file."""
    fw_sections = "\n".join(_render_framework(fw, report) for fw in report.frameworks)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Compliance Report — {_esc(report.project_name)}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         line-height: 1.6; color: #1f2937; max-width: 960px; margin: 0 auto; padding: 2rem; }}
  h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; }}
  h2 {{ font-size: 1.4rem; margin-top: 2rem; margin-bottom: 1rem;
       border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; }}
  h3 {{ font-size: 1.1rem; margin-top: 1.5rem; margin-bottom: 0.5rem; }}
  .meta {{ color: #6b7280; margin-bottom: 2rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  th, td {{ border: 1px solid #e5e7eb; padding: 0.5rem 1rem; text-align: left; }}
  th {{ background: #f9fafb; font-weight: 600; }}
  .badge {{ display: inline-block; padding: 0.15rem 0.6rem; border-radius: 4px;
            color: #fff; font-size: 0.85rem; font-weight: 500; }}
  .rec {{ background: #f3f4f6; padding: 0.5rem 1rem; border-left: 3px solid #3b82f6;
          margin: 0.5rem 0; }}
  .evidence {{ color: #4b5563; font-style: italic; }}
  footer {{ margin-top: 3rem; color: #9ca3af; font-size: 0.85rem; text-align: center; }}
</style>
</head>
<body>

<h1>Compliance Report &mdash; {_esc(report.project_name)}</h1>
<p class="meta">Generated: {_esc(report.generated_at)}</p>

<h2>Overall Summary</h2>
<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr><td>Total controls</td><td>{report.overall_total}</td></tr>
<tr><td>Compliant</td><td>{report.overall_compliant}</td></tr>
<tr><td>Partial</td><td>{report.overall_partial}</td></tr>
<tr><td>Non-compliant</td><td>{report.overall_non_compliant}</td></tr>
<tr><td>Not applicable</td><td>{report.overall_not_applicable}</td></tr>
<tr><td>Not evaluated</td><td>{report.overall_not_evaluated}</td></tr>
<tr><td><strong>Compliance rate</strong></td>\
<td><strong>{report.overall_compliance_rate:.1f}%</strong></td></tr>
</table>

{fw_sections}

<footer>
Generated by <a href="https://github.com/diegofornalha/licit-cli">licit</a>
</footer>

</body>
</html>
"""


def _render_framework(fw: FrameworkReport, report: UnifiedReport) -> str:
    """Render a single framework section as HTML."""
    s = fw.summary
    results_html = "\n".join(
        _render_result(r, report.include_evidence, report.include_recommendations)
        for r in fw.results
    )

    return f"""
<h2>{_esc(fw.name)} ({_esc(fw.version)})</h2>
<p>{_esc(fw.description)}</p>

<table>
<tr><th>Status</th><th>Count</th></tr>
<tr><td>Compliant</td><td>{s.compliant}</td></tr>
<tr><td>Partial</td><td>{s.partial}</td></tr>
<tr><td>Non-compliant</td><td>{s.non_compliant}</td></tr>
<tr><td>Not applicable</td><td>{s.not_applicable}</td></tr>
<tr><td>Not evaluated</td><td>{s.not_evaluated}</td></tr>
<tr><td><strong>Compliance rate</strong></td>\
<td><strong>{s.compliance_rate:.1f}%</strong></td></tr>
</table>

{results_html}
"""


def _render_result(
    result: ControlResult,
    include_evidence: bool,
    include_recommendations: bool,
) -> str:
    """Render a single control result as HTML."""
    status_val = result.status.value
    color = _STATUS_COLORS.get(status_val, "#6b7280")
    ref = result.requirement.article_ref or "N/A"

    evidence_html = ""
    if include_evidence:
        evidence_html = f'<p class="evidence">{_esc(result.evidence)}</p>'

    recs_html = ""
    if include_recommendations and result.recommendations:
        recs_items = "".join(f'<div class="rec">{_esc(r)}</div>' for r in result.recommendations)
        recs_html = f"<div>{recs_items}</div>"

    return f"""
<h3>{_esc(result.requirement.id)}: {_esc(result.requirement.name)}</h3>
<p>
  <span class="badge" style="background:{color}">{_esc(status_val)}</span>
  &nbsp; Reference: {_esc(ref)}
</p>
{evidence_html}
{recs_html}
"""


def _esc(text: str) -> str:
    """Escape HTML special characters including single quotes."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )
