"""Markdown report renderer for unified compliance reports."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from licit.reports.unified import FrameworkReport, UnifiedReport


def render(report: UnifiedReport) -> str:
    """Render a UnifiedReport as Markdown."""
    lines: list[str] = []

    # Header
    lines.append(f"# Compliance Report — {report.project_name}")
    lines.append("")
    lines.append(f"Generated: {report.generated_at}")
    lines.append("")

    # Overall summary
    lines.append("## Overall Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total controls | {report.overall_total} |")
    lines.append(f"| Compliant | {report.overall_compliant} |")
    lines.append(f"| Partial | {report.overall_partial} |")
    lines.append(f"| Non-compliant | {report.overall_non_compliant} |")
    lines.append(f"| Not applicable | {report.overall_not_applicable} |")
    lines.append(f"| Not evaluated | {report.overall_not_evaluated} |")
    lines.append(f"| **Compliance rate** | **{report.overall_compliance_rate:.1f}%** |")
    lines.append("")

    # Per-framework sections
    for fw_report in report.frameworks:
        lines.append(_render_framework(fw_report, report.include_evidence,
                                       report.include_recommendations))

    lines.append("---")
    lines.append("")
    lines.append("*Generated by [licit](https://github.com/diegofornalha/licit-cli)*")
    lines.append("")

    return "\n".join(lines)


def _render_framework(
    fw: FrameworkReport,
    include_evidence: bool,
    include_recommendations: bool,
) -> str:
    """Render a single framework section."""
    lines: list[str] = []
    s = fw.summary

    lines.append(f"## {fw.name} ({fw.version})")
    lines.append("")
    lines.append(fw.description)
    lines.append("")

    # Summary table
    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Compliant | {s.compliant} |")
    lines.append(f"| Partial | {s.partial} |")
    lines.append(f"| Non-compliant | {s.non_compliant} |")
    lines.append(f"| Not applicable | {s.not_applicable} |")
    lines.append(f"| Not evaluated | {s.not_evaluated} |")
    lines.append(f"| **Compliance rate** | **{s.compliance_rate:.1f}%** |")
    lines.append("")

    # Individual results
    for result in fw.results:
        status_icon = _status_icon(result.status.value)
        lines.append(
            f"### {status_icon} {result.requirement.id}: {result.requirement.name}"
        )
        lines.append("")
        lines.append(f"- **Status**: {result.status.value}")
        ref = result.requirement.article_ref or "N/A"
        lines.append(f"- **Reference**: {ref}")

        if include_evidence:
            lines.append(f"- **Evidence**: {result.evidence}")

        if include_recommendations and result.recommendations:
            lines.append("")
            lines.append("**Recommendations:**")
            for rec in result.recommendations:
                lines.append(f"- {rec}")

        lines.append("")

    return "\n".join(lines)


def _status_icon(status: str) -> str:
    """Map status to a text icon for Markdown."""
    icons = {
        "compliant": "[PASS]",
        "partial": "[PARTIAL]",
        "non-compliant": "[FAIL]",
        "n/a": "[N/A]",
        "not-evaluated": "[?]",
    }
    return icons.get(status, "[?]")
